--- #YAML:1.0
name:               Mojolicious-Plugin-HamlRenderer
version:            1.0
abstract:           Haml renderer for Mojolicious
author:
    - Viacheslav Tykhanovskyi <vti@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Mojolicious:  0.999924
    perl:         5.008001
    Text::Haml:   0.990103
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/marcusramberg/mojox-renderer-haml/tree/master
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
